#ifndef _XVM_VERSION_H_
#define _XVM_VERSION_H_ 1

#define XVM_VERSION "0.2.0"
#define XVM_VERSION_MAJOR 0
#define XVM_VERSION_MINOR 2
#define XVM_VERSION_PATCH 0
#define XVM_VERSION_CODE  0x00000200

#endif