#ifndef _XVM_VERSION_H_
#define _XVM_VERSION_H_ 1

#define XVM_VERSION "0.1.0"
#define XVM_VERSION_MAJOR 0
#define XVM_VERSION_MINOR 1
#define XVM_VERSION_PATCH 0
#define XVM_VERSION_CODE  0x00000100

#endif